function testError() {
  try {
    let result = undefinedVariable + 5;
    alert(result);
  } catch (err) {
    alert("ðŸ˜… Oops! Error caught: " + err.message);
  } finally {
    alert("âœ… Finally block executed - no matter what!");
  }
}


