   function testError() {
  try {
    // risky 
    // undefinedVariable = 3
    let result = undefinedVariable + 5;
    alert(result);
  } catch (err) {
    alert("ðŸ˜… Oops! Error caught: " + err.message);
  } finally {
    alert("âœ… Finally block executed - no matter what!");
  }
}



